### PR TITLE
Button reply - Tests written

### PR DESCRIPTION
**Pull request by ianrothmann**
Hi everyone,

Thanks to Derrick for adding the functionality. I did some minor bug fixing, code linting and I've created the Unit and Integration tests and they passed on my side.

Could you perhaps evaluate whether this is satisfactory? It would be great to have the functionality in the repo. Let me know if you want to change anything.

Kind regards,

Ian

### CODE REVIEW

**Comment by aalbarca** [comment]
Hi @ianrothmann thanks a lot for your PR!

Can you check the styleci issue? -> https://github.styleci.io/analyses/N4W3Q1?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link


To avoid this in the future I recommend installing pre-commit and it will automatically correct your code before commit is done.

**Comment by ianrothmann** [comment]
Hi there! Apologies for the oversight, it was an issue with my phpstorm. I have fixed the StyleCI issues now.

**Comment by ianrothmann** [comment]
Hi Team! 

Have you perhaps had a chance to look at this?

Kind regards,

Ian

**Comment by aalbarca** [comment]
merged in https://github.com/netflie/whatsapp-cloud-api/pull/150

**Pull request closed without merging**
