### PR TITLE
Fix optional header for interactive list messages

### PR DESCRIPTION
**Pull request by horatiua**

### CODE REVIEW

**Comment by aalbarca** [comment]
Hi @horatiua 

Thanks for your help and your great work.

The title of the PR does not match the modified code. New features have been added. Was this really your intention or is it a mistake?

Thanks.

**Comment by horatiua** [comment]
Hi,

I only wanted the first commit to be merged.
The second one is another feature, Interactive Button Messages, that are also unavailable via the API.

Thanks!

**Comment by aalbarca** [comment]
Hi @horatiua 

Can you please remove from this PR the commit what you don't want to be merged?

Thanks.

**Comment by aalbarca** [comment]
Fixed in https://github.com/netflie/whatsapp-cloud-api/pull/149

**Pull request closed without merging**
